Vagrant.configure("2") do |config|
    config.vm.communicator = "winrm"
    config.winrm.max_tries = 30000
    config.winrm.retry_delay = 10
    config.winrm.timeout = 30000
    config.vm.guest = :windows
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"
    config.winrm.ssl_peer_verification = false
    config.winrm.transport = :plaintext
    config.winrm.basic_auth_only = true

    config.vm.define "fs" do |fs|
        fs.vm.box = "peru/windows-server-2022-standard-x64-eval"
        fs.vm.box_version = "20230201.01"
        fs.vm.hostname = "fs"
        fs.vm.network :private_network ,
        :type => "dhcp",
        :libvirt__network_name => "internal-win"
        fs.vm.provider :libvirt do |libvirt|
            libvirt.cpus = 4
            libvirt.memory = 8192
            libvirt.driver = "kvm"
        end
    end
    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "fs.yml"
    end
end
