Vagrant.configure("2") do |config|
    config.vm.communicator = "winrm"
    config.winrm.max_tries = 30000
    config.winrm.retry_delay = 10
    config.winrm.timeout = 30000
    config.vm.guest = :windows
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"
    config.winrm.ssl_peer_verification = false
    config.winrm.transport = :plaintext
    config.winrm.basic_auth_only = true

    config.vm.define "dc" do |dc|
        dc.vm.box = "peru/windows-server-2022-standard-x64-eval"
        dc.vm.hostname = "dc"
        dc.vm.network :private_network ,
        :type => "dhcp",
        :libvirt__network_name => "internal-win"
        dc.vm.provider :libvirt do |libvirt|
            libvirt.cpus = 2
            libvirt.memory = 4096
            libvirt.driver = "kvm"
        end
    end
    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "dc.yml"
    end
end
