Vagrant.configure("2") do |config|
    config.vm.define "kali" do |kali|
        kali.vm.box = "kalilinux/rolling"
        kali.vm.hostname = "kali"
        config.vm.synced_folder ".", "/vagrant", disabled: true
        kali.vm.provider :libvirt do |libvirt|
            libvirt.cpus = 2
            libvirt.memory = 4096
            libvirt.driver = "kvm"
        end
    end
    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "kali.yml"
    end
end