Vagrant.configure("2") do |config|
    config.vm.define "podman" do |podman|
        podman.vm.box = "debian/bullseye64"
        podman.vm.hostname = "podman"
        podman.vm.network :private_network ,
        :type => "dhcp",
        :libvirt__network_name => "internal-lin"
        podman.vm.provider :libvirt do |libvirt|
            libvirt.cpus = 2
            libvirt.memory = 4096
            libvirt.driver = "kvm"
        end
    end
    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "podman.yml"
    end
end
